@Dinner.Api_HostAddress = https://localhost:7157
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmY2Q0MTNmMy02NzFiLTQ4ZTItOTk4Ni04NjQ5Njk2MWIzOGQiLCJnaXZlbl9uYW1lIjoiTWlrZSIsImZhbWlseV9uYW1lIjoiWmhhbmciLCJqdGkiOiJkNGNmNDNmMC1kM2I4LTQ5YjMtYTYzMC1lNzNmZGI4NzkxYTEiLCJleHAiOjE3MDg5MTM5NTYsImlzcyI6IkRpbm5lciIsImF1ZCI6IkRpbm5lciJ9.A9-DaHU713gj9Y0wMHXDNeyC0X90ZTLe0syeR0RZ4hM
@hostId = b470616b-5bef-46be-9000-77bd71bdd757

POST {{Dinner.Api_HostAddress}}/hosts/{{hostId}}/menus
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Appetizers",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}