@Dinner.Api_HostAddress = https://localhost:7157
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYjA4NjE1ZC02YTNhLTRmNTYtOGFkZi1hODNhNmQ1Yjc0YjgiLCJnaXZlbl9uYW1lIjoiTWlrZSIsImZhbWlseV9uYW1lIjoiWmhhbmciLCJqdGkiOiI3ZGNlMWRjMi1lMmVhLTQ0ODAtOTM5MC1kYTBjMmY0ODAzZjEiLCJleHAiOjE3MDg5MDkyODYsImlzcyI6IkRpbm5lciIsImF1ZCI6IkRpbm5lciJ9.JNr-LNBpZQGpNv2X0FybXRhSVjWZviKxTa0qGix7OKw
@hostId = b470616b-5bef-46be-9000-77bd71bdd757

POST {{Dinner.Api_HostAddress}}/hosts/{{hostId}}/menus
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Appetizers",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}