@Dinner.Api_HostAddress = https://localhost:7157

GET {{Dinner.Api_HostAddress}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NGVkYWYxMS1lNDk5LTRmMWQtODIwNC1hMmNjNzkxZGQwYmIiLCJnaXZlbl9uYW1lIjoiTWlrZSIsImZhbWlseV9uYW1lIjoiWmhhbmciLCJqdGkiOiI5ZDhiYWZjYy1iNTgzLTQ5ZWYtYWJhNy00NTE3MzBlOWUxMWEiLCJleHAiOjE3MDY0ODY4MDgsImlzcyI6IkRpbm5lciIsImF1ZCI6IkRpbm5lciJ9.xNQU4i61pdQGuvtDoW3X4wi8IRoefzlvP_5oMYiCnvw