@Dinner.Api_HostAddress = https://localhost:7157

GET {{Dinner.Api_HostAddress}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYjA4NjE1ZC02YTNhLTRmNTYtOGFkZi1hODNhNmQ1Yjc0YjgiLCJnaXZlbl9uYW1lIjoiTWlrZSIsImZhbWlseV9uYW1lIjoiWmhhbmciLCJqdGkiOiI3ZGNlMWRjMi1lMmVhLTQ0ODAtOTM5MC1kYTBjMmY0ODAzZjEiLCJleHAiOjE3MDg5MDkyODYsImlzcyI6IkRpbm5lciIsImF1ZCI6IkRpbm5lciJ9.JNr-LNBpZQGpNv2X0FybXRhSVjWZviKxTa0qGix7OKw